/* eslint-disable max-len */
const config = {
	cardDetails: [
		{
			img: '/image/9.jpeg',
			video: '/video/testVc.mp4',
			icon: '/channelIcon/2.jpeg',
			videoName: 'Best Youtube Thumbnail of 2022 ',
			channelName: 'Tamil TechLancer',
			views: '45K views',
			time: '1 year ago',
			id: 123,
		},
		{
			img: '/image/8.jpeg',
			video: '/video/testVc.mp4',
			icon: '/channelIcon/1.jpeg',
			videoName: 'Make Professional Youtube Thumbnail',
			channelName: 'Tamil TechLancer',
			views: '19K views',
			time: '5 days ago',
			id: 234,
		},
		{
			img: '/image/10.jpg',
			video: '/video/testVc.mp4',
			icon: '/channelIcon/2.jpeg',
			videoName: 'Relax your mind',
			channelName: 'Isha',
			views: '78K views',
			time: '58 minutes ago',
			id: 345,
		},
		{
			img: '/image/1.jpeg',
			icon: '/channelIcon/1.jpeg',
			videoName: 'Six ways to Use Time Efficiently',
			channelName: 'TimeX',
			views: '58K views',
			time: '28 minutes ago',
			id: 456,
		},
		{
			img: '/image/12.jpg',
			icon: '/channelIcon/2.jpeg',
			videoName: 'Natural Beauty',
			channelName: 'MotherNature',
			views: '12K views',
			time: '8 hours ago',
			id: 567,
		},
		{
			img: '/image/3.jpeg',
			icon: '/channelIcon/3.jpeg',
			videoName: 'Master HTML and CSS ',
			channelName: 'AstroX',
			views: '18K views',
			time: '1 hour ago',
			id: 678,
		},
		{
			img: '/image/4.jpeg',
			icon: '/channelIcon/1.jpeg',
			videoName: 'Evergreen Songs 2022',
			channelName: 'Isaimini',
			views: '10K views',
			time: '6 hours ago',
			id: 789,
		},

		{
			img: '/image/7.jpg',
			icon: '/channelIcon/3.jpeg',
			videoName: '10 Best Windows Background',
			channelName: 'VP Tube',
			views: '2K views',
			time: '15 hours ago',
			id: 910,
		},
		{
			img: '/image/11.jpg',
			icon: '/channelIcon/3.jpeg',
			videoName: 'Best Youtube Thumbnail of 2022',
			channelName: 'Tamil TechLancer',
			views: '45K views',
			time: '1 year ago',
			id: 101,
		},
	],
	categories: [
		'All',
		'Gaming',
		'Computer Programming',
		'Music',
		'AI',
		'GAdgets',
		'Naruto',
		'Podcasts',
		'News',
		'Business',
		'Video editing',
		'Sales',
		'Cinema',
		'Avengers',
		'Anime',
		'Attack on Titan',
	],
};

export default config;
