const config = {
	cardDetails: [
		{
			img: '/image/1.jpeg',
			icon: '/channelIcon/1.jpeg',
			videoName: 'Six ways to Use Time Efficiently',
			channelName: 'TimeX',
			views: '58K views',
			time: '28 minutes ago',
		},
		{
			img: '/image/10.jpg',
			icon: '/channelIcon/2.jpeg',
			videoName: 'Relax your mind',
			channelName: 'Isha',
			views: '78K views',
			time: '58 minutes ago',
		},
		{
			img: '/image/3.jpeg',
			icon: '/channelIcon/3.jpeg',
			videoName: 'Master HTML and CSS',
			channelName: 'AstroX',
			views: '18K views',
			time: '1 hour ago',
		},
		{
			img: '/image/4.jpeg',
			icon: '/channelIcon/1.jpeg',
			videoName: 'Evergreen Songs 2022',
			channelName: 'Isaimini',
			views: '10K views',
			time: '6 hours ago',
		},
		{
			img: '/image/12.jpg',
			icon: '/channelIcon/2.jpeg',
			videoName: 'Natural Beauty',
			channelName: 'MotherNature',
			views: '12K views',
			time: '8 hours ago',
		},
		{
			img: '/image/7.jpg',
			icon: '/channelIcon/3.jpeg',
			videoName: '10 Best Windows Background',
			channelName: 'VP Tube',
			views: '2K views',
			time: '15 hours ago',
		},
		{
			img: '/image/8.jpeg',
			icon: '/channelIcon/1.jpeg',
			videoName: 'Make Professional Youtube Thumbnails',
			channelName: 'Tamil TechLancer',
			views: '19K views',
			time: '5 days ago',
		},
		{
			img: '/image/9.jpeg',
			icon: '/channelIcon/2.jpeg',
			videoName: 'Best Youtube Thumbnail of 2022',
			channelName: 'Tamil TechLancer',
			views: '45K views',
			time: '1 year ago',
		},
		{
			img: '/image/11.jpg',
			icon: '/channelIcon/3.jpeg',
			videoName: 'Best Youtube Thumbnail of 2022',
			channelName: 'Tamil TechLancer',
			views: '45K views',
			time: '1 year ago',
		},
	],
};

export default config;
